services:
  postgres:
    image: postgres:16-alpine
    container_name: finance_monitoring_db
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: finance
      POSTGRES_PASSWORD: finance
      POSTGRES_DB: finance_monitoring
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
